# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Using official Node.js LTS Alpine image
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and lockfile
COPY package.json package-lock.json ./

# Install dependencies and build
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /usr/src/app

# Copy built files and dependencies
COPY --from=builder /usr/src/app/build ./build
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Default command
ENTRYPOINT ["node", "build/index.js"]
